# DefaultContentLanguage = "en"
baseURL = "http://www.bitwise-it.dk/"
enableEmoji = false
title = "bitwise"
#theme = "beautifulhugo"
theme = "bitwise"

uglyurls = false
disableSitemap = true
#disableKinds= ["sitemap"]
# defaultExtension = ""

[Params]
  Author = "Bjørn Rosell"

[taxonomies]
  tag = "tags"
  category = "categories"

[blackfriday]
  hrefTargetBlank = true
  extensions = ["noEmptyLineBeforeBlock"]
  fractions = true
  # List of extensions:
  # https://godoc.org/gopkg.in/rtfb/blackfriday.v2#Extensions 
  # beware to camelCase them...


#[[menu.main]]
#    name = "Home"
#    weight = -110
#    url = "/"

[Languages]
[Languages.en]
weight = 2
languageCode = "en"
languageName = "english"

[Languages.da]
weight = 1
languageCode = "da"
languageName = "dansk"


